<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Demystifying Email Design</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="margin: 0; padding: 0; font-family: sans-serif">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td>
            <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="padding: 40px 30px 40px 30px; background-color: #ff5252; color: #ffffff; font-weight: 600;">
                       Confirme your Email address
                    </td>
                </tr>
                <tr>
                    <td style="padding: 40px 30px 40px 30px;">
                        <table border="0" cellpadding="0" cellspacing="0" width="100%">
                            <tr>
                                <td style="text-align: center;">
                                    <a href="http://localhost:8081/confirmed?email=${email}&token=${token}" 
                                       style="font-weight: 600; border-radius: 10px; background: #039be5; padding: 10px 40px 10px 40px; color: #ffffff;: #ffffff;text-decoration: none">Confirmed</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 40px 30px 40px 30px; background-color: #eeeeee; color: #adadad; font-weight: 600;">
                        Hint: Tap to link to confirme that you registered on site
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>